pipeline {
    agent any
    stages {
        stage ('Build Application') {
            step {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }

        }
        stage ('Deploy to the stageing Environment') {
            build job: 'Deploying_Tomcat_to_staging'
        }
    }
}